#!/usr/bin/env python
import subprocess
import os
import sys

def main():
    pylint_cfg_path = os.path.join( os.path.dirname(\
                        os.path.abspath(__file__)), 'conf')
    pylint_cfg_fname = 'pylint_vauxoo.cfg'
    workdir = os.getcwd()

    #Fix pylint path. More info: 
    #    https://www.mail-archive.com/code-quality@python.org/msg00294.html
    fpath_main_init = os.path.join(workdir, '__init__.py')
    if not os.path.isfile( fpath_main_init ):
        open(fpath_main_init, "w")
    os.environ['PYTHONPATH'] += ":"+workdir #TODO: win compatibility
    #TODO: Set environment odoo path
    #TODO: Get log
    pylint_cfg_fname_path = os.path.join( pylint_cfg_path, pylint_cfg_fname)
    if os.path.isfile( pylint_cfg_fname_path ):
        cmd = "pylint --rcfile=%s %s"%(pylint_cfg_fname_path, workdir)
        print "cmd", cmd
        subprocess.check_call(cmd, shell=True)
    else:
        print "File not exists [%s]"%( pylint_cfg_fname_path )#TODO: log error
    return 0

if __name__ == '__main__':
    exit(main())